version: '3.9'

services:
  nest:
    build:
      context: ./infrastructure/plateforms/Backend/nest
      dockerfile: dockerfile
    container_name: nest_service
    ports:
      - "3000:3000"
    volumes:
      - ./infrastructure/plateforms/Backend/nest:/app/infrastructure/plateforms/Backend/nest
      - ./application:/app/application
      - ./domain:/app/domain
      - ./infrastructure:/app/infrastructure
      - /app/infrastructure/plateforms/Backend/nest/node_modules
    environment:
      - NODE_ENV=production

  node:
    build:
      context: ./infrastructure/plateforms/Backend/express
      dockerfile: dockerfile
    container_name: express_service
    ports:
      - "3001:3001"
    volumes:
      - ./infrastructure/plateforms/Backend/express:/app/infrastructure/plateforms/Backend/express
      - ./application:/app/application
      - ./domain:/app/domain
      - ./infrastructure:/app/infrastructure
      - /app/infrastructure/plateforms/Backend/express/node_modules
    environment:
      - NODE_ENV=environment

  next:
    build:
      context: ./infrastructure/plateforms/frontend/front-react
      dockerfile: dockerfile
    container_name: next_service
    platform: linux/amd64
    ports:
      - "80:3000"
    volumes:
      - ./infrastructure/plateforms/frontend/front-react:/app/infrastructure/plateforms/frontend/front-react
      - /app/infrastructure/plateforms/frontend/front-react/node_modules
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=moto_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:8.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
        - "8080:8080"


volumes:
  postgres_data:
  mongo_data:
