# Étape 1 : Utiliser Node.js comme image de base
FROM node:18

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copier uniquement les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source dans le conteneur
COPY . .

# Construire le projet
RUN npm run build

# Exposer le port utilisé par l'application
EXPOSE 3000

# Commande par défaut pour démarrer l'application
CMD ["npm", "run", "start:dev"]