FROM node:20.10.0-alpine

WORKDIR /app/infrastructure/plateforms/Backend/express

COPY package*.json ./

#ENV NODE_ENV=development

RUN npm install

RUN npm install --save-dev tsx nodemon

COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev"]
