FROM node:18 AS build

WORKDIR /app/infrastructure/plateforms/frontend/front-react

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18 AS production

WORKDIR /app/infrastructure/plateforms/frontend/front-react

# Copier les dépendances et le build depuis l'étape de build
#COPY --from=build /app/infrastructure/plateforms/frontend/front-react/package.json /app/package-lock.json ./
#COPY --from=build /app/infrastructure/plateforms/frontend/front-react/.next ./.next
#COPY --from=build /app/infrastructure/plateforms/frontend/front-react/public ./public
#COPY --from=build /app/infrastructure/plateforms/frontend/front-react/node_modules ./node_modules

ENV PORT=80

EXPOSE 80

CMD ["npm", "run", "dev"]